### ISSUE TITLE
Amber rebuild error

### ISSUE THREAD

**Issue by just1602** [riseupnet/riseup_help#180]
When I run `amber rebuild` I got this error:

```
/usr/local/lib64/ruby/gems/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)
	from /usr/local/lib64/ruby/gems/2.1.0/gems/i18n-0.7.0/lib/i18n/config.rb:34:in `default_locale='
	from /usr/local/lib64/ruby/gems/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:35:in `default_locale='
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/site_configuration.rb:96:in `cleanup'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/site_configuration.rb:79:in `initialize'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/site_configuration.rb:46:in `new'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/site_configuration.rb:46:in `load'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/site.rb:17:in `initialize'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/cli.rb:40:in `new'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/lib/amber/cli.rb:40:in `rebuild'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/bin/amber:79:in `main'
	from /usr/local/lib64/ruby/gems/2.1.0/gems/amber-0.3.3/bin/amber:82:in `<top (required)>'
	from /usr/local/bin/amber:23:in `load'
	from /usr/local/bin/amber:23:in `<main>'
```

I run ruby 2.1.5 and amber 0.3.3.

**Comment by elijh** [comment]
This should be resolved with amber 0.3.4. try `sudo gem update amber`
