### ISSUE TITLE
navbar commit makes amber unhappy

### ISSUE THREAD

**Issue by wxl** [riseupnet/riseup_help#430]
the navbar commit (676392a92cdba1b3b3bb6b63beb96bafd5089205) results in malfunctions with amber, at least with ruby 2.3. if i `checkout` previous commits (such as 349eb5cfd6a75c7fa7333fef08b207c28b3b52c9), there is no such issue.

the particular error (which repeats itself) from amber is:
```
ERROR: undefined method `link_to' for #<Amber::Render::View:0xf5bb187c>
Did you mean?  link
ERROR: /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:4:in `block in singleton class'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131062:in `instance_eval'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131062:in `singleton class'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131060:in `__tilt_739184650'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/haml.rb:19:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:128:in `render_haml'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:73:in `render_html'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:55:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/view.rb:70:in `render'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:15:in `block in singleton class'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131063:in `instance_eval'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131063:in `singleton class'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131061:in `__tilt_739184650'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/haml.rb:19:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/layout.rb:46:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/view.rb:66:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:131:in `block (2 levels) in render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `open'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `block in render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `each'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:35:in `render_to_file'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/server.rb:139:in `render_page'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/server.rb:64:in `do_GET'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpservlet/filehandler.rb:214:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by elijh** [comment]
it works with a the latest master branch of the amber code. I will push a release soon. sorry about that.

**Comment by wxl** [comment]
I am still having problems with latest master FWIW:

```
ERROR: undefined method `link_to' for #<Amber::Render::View:0xf61d765c>
Did you mean?  link
ERROR: /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:4:in `block in singleton class'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131062:in `instance_eval'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131062:in `singleton class'
       /home/wxl/git/riseup_help/amber/layouts/_riseup_bar.html.haml:131060:in `__tilt_85822238'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/haml.rb:19:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:128:in `render_haml'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:73:in `render_html'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/template.rb:55:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/view.rb:70:in `render'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:15:in `block in singleton class'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131063:in `instance_eval'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131063:in `singleton class'
       /home/wxl/git/riseup_help/amber/layouts/home.html.haml:131061:in `__tilt_85822238'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/haml.rb:19:in `evaluate'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/layout.rb:46:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/render/view.rb:66:in `render'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:131:in `block (2 levels) in render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `open'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `block in render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `each'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `render_content_files'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/static_page/render.rb:35:in `render_to_file'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/server.rb:139:in `render_page'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/amber-0.3.11/lib/amber/server.rb:64:in `do_GET'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpservlet/filehandler.rb:214:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
       /home/wxl/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```
